# fly.toml app configuration file generated for holy-cherry-4553 on 2023-09-12T02:21:11+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holy-cherry-4553"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
